In [1]:
from pyspark.sql import SparkSession

In [2]:
spark = SparkSession.builder.appName('date').getOrCreate()

In [3]:
df = spark.read.csv('FileStore/tables/appl_stock.csv', header=True, inferSchema=True)

In [4]:
df.printSchema()

In [5]:
df.show()

In [6]:
from pyspark.sql.functions import dayofmonth, hour, dayofyear, month, year, weekofyear, format_number, date_format

In [7]:
df.select(month(df['Date'])).show()

In [8]:
# df.select(year(df['Date'])).show()
newdf = df.withColumn('year', year(df['Date']))

In [9]:
results = newdf.groupBy('year').mean().select(['year', 'avg(Close)'])

In [10]:
results = results.withColumnRenamed('avg(Close)', 'avg close price')

In [11]:
results.select(['year', format_number('avg close price', 2).alias('avg close price')]).show()