In [1]:
from pyspark.sql import SparkSession

In [2]:
spark = SparkSession.builder.appName('miss').getOrCreate()

In [3]:
df = spark.read.csv('FileStore/tables/ContainsNull.csv', inferSchema=True, header=True)

In [4]:
df.printSchema()

In [5]:
df.show()

In [6]:
# df.na.drop(how='any').show()
# df.na.drop(thresh=2).show()
df.na.drop(subset='Sales').show()

In [7]:
df.na.fill('No Name', subset=['Name']).show()

In [8]:
from pyspark.sql.functions import mean

In [9]:
mean_val = df.select(mean(df['Sales'])).collect()

In [10]:
mean_sales = mean_val[0][0]

In [11]:
df.na.fill(mean_sales, subset=['Sales']).show()

In [12]:
df.na.fill(df.select(mean(df['Sales'])).collect()[0][0], subset='Sales').show()